language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: vNPuW33T01Aeu721g7daSK73mVQ9hQZ4drV8skQnnOUOZvCTnK2v4EfadcUoXxLE2uDzHWeZm5KARWzIUvtNpXTqH6ZZb4srYHuVsb5dRv/3FnksICM4tTXknVjF3rLK5ToxIUsYdG3+bN3h9jm0t3GwQgVUhM7qng6E6WYMNLxu4XL4e+V6GTWAoFm+eeolNXHJFyKBJfSMOFwdW5OY3ZQPJeBO24hjqGEfz3IhkdO4hDp73cHVVydIqzRWcXsw/OffFT292xwkANjTW5/jJKJcztmTlDSEr6xGV6TVKBS4x7HDo2J6+NAXzF5bKcclqZ9IaRfacvBb+4A4Ri/gUjHNDOAMj6HK6LNJMQlngHSBxrLeQC4WbC67FiAFaDtCneDX5t7MalEE6jqrX620LeePiZ5rPBlvDKyj+cDV4TrWTU41m6LxfuLqWwnFVV/BaFOruPYe75KSU0sQ4qOyyur+n8lbreK3PoOD3buQb3+WEQV+wTjqK2ftbyrPzoa2Nx6CoiZNnY9/Uiay5AN28rthDbLNRKJLh4ETbNZA2ZKj+nyOrPOGzkXR3UwLifVbSs8SRsqeX4y4yerUtqUWPA71u9kfFeU0f77GHk81PGlNfd7uAIL9DfflIz1xrMkTdZ2ny7SpKkBCSoymoc3pEXGio/DOmpIl71Mo7iyfH9A=
  app: sample-travis-heroku-repo2
  on:
    repo: pphan93/sample-travis-heroku-repo2
env:
  global:
  - secure: vNPuW33T01Aeu721g7daSK73mVQ9hQZ4drV8skQnnOUOZvCTnK2v4EfadcUoXxLE2uDzHWeZm5KARWzIUvtNpXTqH6ZZb4srYHuVsb5dRv/3FnksICM4tTXknVjF3rLK5ToxIUsYdG3+bN3h9jm0t3GwQgVUhM7qng6E6WYMNLxu4XL4e+V6GTWAoFm+eeolNXHJFyKBJfSMOFwdW5OY3ZQPJeBO24hjqGEfz3IhkdO4hDp73cHVVydIqzRWcXsw/OffFT292xwkANjTW5/jJKJcztmTlDSEr6xGV6TVKBS4x7HDo2J6+NAXzF5bKcclqZ9IaRfacvBb+4A4Ri/gUjHNDOAMj6HK6LNJMQlngHSBxrLeQC4WbC67FiAFaDtCneDX5t7MalEE6jqrX620LeePiZ5rPBlvDKyj+cDV4TrWTU41m6LxfuLqWwnFVV/BaFOruPYe75KSU0sQ4qOyyur+n8lbreK3PoOD3buQb3+WEQV+wTjqK2ftbyrPzoa2Nx6CoiZNnY9/Uiay5AN28rthDbLNRKJLh4ETbNZA2ZKj+nyOrPOGzkXR3UwLifVbSs8SRsqeX4y4yerUtqUWPA71u9kfFeU0f77GHk81PGlNfd7uAIL9DfflIz1xrMkTdZ2ny7SpKkBCSoymoc3pEXGio/DOmpIl71Mo7iyfH9A=
