language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  app: sample-travis-heroku-repo2
  on:
    repo: pphan93/sample-travis-heroku-repo2
env:
  global:
  - secure: YM6R46Sg+W2lyun/l41dIoo1kptpJo7WQgPmItyb+f1OfI7UZl0XMJ8L4Xd/gPp6EVwHL9XQr8EtJSOj/RJyRXjWuroQi1JPODvISymOIDZKYwOyKSSOzMqdZy0qvoSd5E5zrTYRCvEV8KGS4cGvuaRtHDgvSarZSlZp4CSUJSapQIxEd+ijTbhMDYOuX7dYnJWGc0/eZZfFGJsyviV0tfc5fqGMm2q7upekj9ffIjzCOvi0MmoSjtoXruzq+rUZ++2j9OirWNDOxkWPDcaDyii/6AO+ue2XfCj6fSSx6L0lCLESH/qIU/0SvZ7sWi8WmDhKxpWOJ4rZEOZu4VCzJgeY6sSQBggb+OPEthOPZa7vya8vQluvqRCqHHBCC6vyzcF48YOLbp5HctZdrFGXS2odaFTlsEFg/QVrXuRLBvrpBHko8TNVQnvufHx755OeglH7FJf92QT44P+EfGqI5DoUgTwLlyYwUoVVaEg+fpMpc9qRgiXUTEHX5ctP0brarrrhMCJzjsXyVBGoGDq31Ix1btLWU1vrQp60g4JLW0bmjCTXD7s+Z9d824IQPRVucR5ITMR68wRfHO7uS7zHY8hqblhJVu68SlbdnUNS71tYJ+6Lm/uyAiJqlzWpNHcP7SkEF7jM7TOH19ALdTgYWMRR6uNg1i5tjaR6aJlxpXU=
