language: node_js
node_js:
- stable
npm: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: "dZqmVkxUs2+DCNTIwBjvqzMfXARsET9pKf8NQBCRjRriKifoFecyAC8K7+FqF2yb/wr2VtE6z/yMOz/nFpWAznHrGXHZhnu9LDeBJ6m3pxKs8H6DnpBME/QRNmRbgd+FuOyB1JBQWKUeqy8ZiMwxZzN4uMJao8bRGXwajUInWXLydUaPv7l/6/RLNR0kqlI2bR4PwHhq3bSBsrgzKPP99IBQjKfUoaHd7jau0u1ztG6apbajj5WRXNWO56n/vl5XIGJvqM2WJ1gmvm4QHZdmimJNbU5+dGD4k72CTCG1ohF7OtQB2hWG8TzeJUMo1Mcsgh4YWQYVln0uxI6ug7Sne9vplJn49Ge5xHrHKkZLyB2jk0zz7gkTkMq/7MosmtwhA4wqWLeBoYFa8MJLfraV1tXDG9A0949Hl7luIclXGkqXfgZq0+9gU5tZPpFUSrY3y53u05YcDSuxhLeM0d7TD99hmcmflzhvStuvQ5hWq9IlbY/T61e2MHIXt+avJNDkjAkOMCdhUlayo+4z23w2xgjSyVWpCzOlSyzaxHuHk1eHZ3G3Y9odVwssamxSEHv3996LlXcTZVmM3CW77KYmnhv65nYbnVyYUmP862kmxb1xQQunJqh2NXLMfqmw5ULhyUhhImUQRtBgWgcxHim9nk91kA09tuLXSGqtTWi3onc="
  app: limitless-cove-84552
  on:
    repo: pphan93/sample-travis-heroku-repo2
